### PR TITLE
Create bucket if missing in CreateDatabaseIfNotExists

### LINKED ISSUE #13: Support CreateDatabaseIfNotExistsAsync To Create a Bucket
The end-to-end query tests currently work by preloading data using this method.

### PR DESCRIPTION
**Pull request by brantburnett**
Also implement provider configuration in CouchbaseTestStore.

fixes #13

### CODE REVIEW

**Comment by mgroves** [comment]
Thank you @brantburnett for the PR!

Looks like the implementation is working, although not all the tests are passing (not sure if you meant for them to be passing yet). Also, I noticed something strange. The buckets created by the test show up in Couchbase with missing "Documents/Statistics" links (see screenshot). Any idea why that would be?

issue13screenshot

**Comment by mgroves** [comment]
Nevermind on that screenshot, the links showed up eventually. Probably because so many buckets

**Comment by brantburnett** [comment]
Yes, I do not expect all the tests to pass. I only implemented the create bucket logic, not the collection stuff. Additionally, it appears that you can only run either the sync or the async tests at once.  If you run both, they interfere with each other. I'm assuming MS has some way to filter those runs, haven't figured it all out yet.

**Comment by mgroves** [comment]
Thanks, @brantburnett, it looks good!

**Pull request merged**
